runmode: debug                          # run mode: debug, release, test. this will cover by env: GIN_MODE
port: 34565                             # HTTP port will cover by env ENV_WEB_HOST_PORT and most in docker use env ENV_WEB_HOST_PORT

name: gin-api-swagger-temple            # name of API Server
api_base: http://0.0.0.0:34565        # url full ip:port, this will cover by env: ENV_WEB_AUTO_HOST=true, if in docker do not open this env
base_path: /api/v1                      # /v1 is api MAJOR version as https://semver.org/
sslEnable: false                        # isEnable ssl mode, this will cover by env: ENV_WEB_HTTPS_ENABLE

# zap config
zap:
  AtomicLevel: -1 # DebugLevel:-1 InfoLevel:0 WarnLevel:1 ErrorLevel:2
  Api:
    PrefixPaths: "/api/v1/" # api path prefix list
    AtomicLevel: 0 # DebugLevel:-1 InfoLevel:0 WarnLevel:1 ErrorLevel:2 default 0
  FieldsAuto: false # is use auto Fields key set
  Fields:
    Key: key
    Val: val
  Development: true #  is open file and line number
  Encoding: console # output format, only use console or json, default is console
  rotate:
    Filename: logs/gin-api-swagger-temple.log # Log file path
    MaxSize: 16 # Maximum size of each zlog file, Unit: M
    MaxBackups: 10 # How many backups are saved in the zlog file
    MaxAge: 7 # How many days can the file be keep, Unit: day
    Compress: true # need compress
  EncoderConfig:
    TimeKey: time
    LevelKey: level
    NameKey: logger
    CallerKey: caller
    MessageKey: msg
    StacktraceKey: stacktrace
    TimeEncoder: ISO8601TimeEncoder # ISO8601TimeEncoder EpochMillisTimeEncoder EpochNanosTimeEncoder EpochTimeEncoder default is ISO8601TimeEncoder
    EncodeDuration: SecondsDurationEncoder # NanosDurationEncoder SecondsDurationEncoder StringDurationEncoder default is SecondsDurationEncoder
    EncodeLevel: CapitalColorLevelEncoder # CapitalLevelEncoder CapitalColorLevelEncoder LowercaseColorLevelEncoder LowercaseLevelEncoder default is CapitalLevelEncoder
    EncodeCaller: ShortCallerEncoder # ShortCallerEncoder FullCallerEncoder default is FullCallerEncoder

monitor: # monitor
  status: true             # api status use {monitor.health}
  health: /status/health   # api health
  retryCount: 10           # ping api health retry count
  hardware: true           # hardware true or false
  status_hardware:
    disk: /status/hardware/disk     # hardware api disk
    cpu: /status/hardware/cpu       # hardware api cpu
    ram: /status/hardware/ram       # hardware api ram
  debug: true                       # debug true or false
  pprof: true                       # pprof true or false
  security: false                   # debug and security security true or false
  securityUser:
    admin: f6011b78008fd971784bNEEDCHANGE # admin:pwd

swagger:                            # swagger not show at release
  api_major_version: v1             # api MAJOR version as https://semver.org/
  root: /swagger                    # swagger root
  ui_root: /editor                  # swagger ui root
  index: /swagger/editor/index.html # swagger index as ${root}${ui_root}/index.html
  security: false                   # swagger security true or false
  user:                             # swagger user setting of BasicAuth
    admin: 36116f7c73bc9acb2a7a26   # admin:pwd
    user: e2236a11aceac4de          # user:pwd

