basePath: /api/v1
definitions:
  biz.Biz:
    properties:
      id:
        example: id123zqqeeadg24qasd
        type: string
      info:
        example: input info here
        type: string
      limit:
        example: 10
        type: integer
      offset:
        example: 0
        type: integer
    type: object
  errdef.Err:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@sinlov.cn
    name: API Support
    url: http://github.com/
  description: This is a sample server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://github.com/
  title: gin-api-swagger-temple
  version: v1.x.x
paths:
  /biz/json:
    get:
      consumes:
      - application/json
      description: warning api in prod will hide, abs remote api for dev
      produces:
      - application/json
      responses:
        "200":
          description: value in biz.Biz
          schema:
            $ref: '#/definitions/biz.Biz'
        "500":
          description: Internal Server Error
      summary: /biz/json
      tags:
      - biz
  /biz/modelBiz:
    post:
      consumes:
      - application/json
      description: warning api in prod will hide, abs remote api for dev
      parameters:
      - description: body biz.Biz for post
        in: body
        name: biz
        required: true
        schema:
          $ref: '#/definitions/biz.Biz'
      produces:
      - application/json
      responses:
        "200":
          description: value in biz.Biz
          schema:
            $ref: '#/definitions/biz.Biz'
        "400":
          description: error at errdef.Err
          schema:
            $ref: '#/definitions/errdef.Err'
      summary: /biz/modelBiz
      tags:
      - biz
  /biz/path/{some_id}:
    get:
      consumes:
      - application/json
      description: warning api in prod will hide, abs remote api for dev
      parameters:
      - description: some id to show
        in: path
        name: some_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: value in biz.Biz
          schema:
            $ref: '#/definitions/biz.Biz'
        "400":
          description: error at errdef.Err
          schema:
            $ref: '#/definitions/errdef.Err'
      summary: /biz/path
      tags:
      - biz
  /biz/query/:
    get:
      consumes:
      - application/json
      description: warning api in prod will hide, abs remote api for dev
      parameters:
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: value in biz.Biz
          schema:
            $ref: '#/definitions/biz.Biz'
        "400":
          description: error at errdef.Err
          schema:
            $ref: '#/definitions/errdef.Err'
      summary: /biz/query
      tags:
      - biz
  /biz/string:
    get:
      description: get string of this api.
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: /biz/string
      tags:
      - biz
securityDefinitions:
  BasicAuth:
    type: basic
  WithToken:
    description: Please set the token of the API, note that it starts with "Bearer"
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
