basePath: /api/v1
definitions:
  biz.Biz:
    properties:
      id:
        default: id123zqqeeadg24qasd
        example: id123zqqeeadg24qasd
        type: string
      info:
        default: info
        example: input info here
        type: string
      limit:
        default: 10
        example: 10
        type: integer
      offset:
        default: 0
        example: 0
        type: integer
    type: object
  errdef.Err:
    properties:
      code:
        description: |-
          Code
          error code default 0 is OK
        example: 0
        type: integer
      msg:
        description: |-
          Msg
          error message, if OK is empty
        example: msg of error code 0 is empty
        type: string
    required:
    - code
    type: object
  parse_http.FormContent:
    properties:
      headers:
        additionalProperties:
          type: string
        type: object
      host:
        type: string
      method:
        type: string
      param:
        type: string
      parse_time:
        type: string
      postData:
        additionalProperties:
          type: string
        type: object
      proto:
        type: string
      proto_major:
        type: integer
      proto_minor:
        type: integer
      queryString:
        additionalProperties:
          type: string
        type: object
      referer:
        type: string
      remote_addr:
        type: string
      url:
        type: string
    type: object
  parse_http.HeaderContent:
    properties:
      header:
        type: string
      headers:
        additionalProperties:
          type: string
        type: object
      host:
        type: string
      method:
        type: string
      param:
        type: string
      parse_time:
        type: string
      proto:
        type: string
      proto_major:
        type: integer
      proto_minor:
        type: integer
      referer:
        type: string
      remote_addr:
        type: string
      url:
        type: string
    type: object
  parse_http.QueryContent:
    properties:
      headers:
        additionalProperties:
          type: string
        type: object
      host:
        type: string
      method:
        type: string
      param:
        type: string
      parse_time:
        type: string
      proto:
        type: string
      proto_major:
        type: integer
      proto_minor:
        type: integer
      queryString:
        additionalProperties:
          type: string
        type: object
      referer:
        type: string
      remote_addr:
        type: string
      url:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@sinlov.cn
    name: API Support
    url: http://github.com/
  description: This is a sample server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://github.com/
  title: gin-api-swagger-temple
  version: v1.x.x
paths:
  /biz/form:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: warning api in prod will hide, abs remote api for dev
      parameters:
      - default: id123zqqeeadg24qasd
        example: id123zqqeeadg24qasd
        in: formData
        name: id
        type: string
      - default: info
        example: input info here
        in: formData
        name: info
        type: string
      - default: 10
        example: 10
        in: formData
        name: limit
        type: integer
      - default: 0
        example: 0
        in: formData
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: value in model.Biz
          schema:
            $ref: '#/definitions/biz.Biz'
        "400":
          description: error at errdef.Err
          schema:
            $ref: '#/definitions/errdef.Err'
      summary: 'api demo form with: x-www-form-urlencoded'
      tags:
      - biz
  /biz/form_full:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: for biz
      parameters:
      - default: foo
        description: form item foo
        in: formData
        name: foo
        required: true
        type: string
      - default: bar
        description: form item bar
        in: formData
        name: bar
        required: true
        type: string
      - default: baz
        description: form item baz
        in: formData
        name: baz
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: value in parse_http.FormContent
          schema:
            $ref: '#/definitions/parse_http.FormContent'
        "400":
          description: error at errdef.Err
          schema:
            $ref: '#/definitions/errdef.Err'
      summary: /biz/form_full
      tags:
      - biz
  /biz/header_full:
    get:
      consumes:
      - text/plain
      description: for biz
      parameters:
      - default: foo
        description: 'header BIZ_FOO '
        in: header
        name: BIZ_FOO
        required: true
        type: string
      - default: bar
        description: 'header BIZ_BAR '
        in: header
        name: BIZ_BAR
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: value in parse_http.HeaderContent
          schema:
            $ref: '#/definitions/parse_http.HeaderContent'
        "400":
          description: error at errdef.Err
          schema:
            $ref: '#/definitions/errdef.Err'
      summary: /biz/header_full
      tags:
      - biz
  /biz/json:
    get:
      consumes:
      - application/json
      description: warning api in prod will hide, abs remote api for dev
      produces:
      - application/json
      responses:
        "200":
          description: value in biz.Biz
          schema:
            $ref: '#/definitions/biz.Biz'
        "500":
          description: ""
      summary: api demo json
      tags:
      - biz
  /biz/modelBiz:
    post:
      consumes:
      - application/json
      description: warning api in prod will hide, abs remote api for dev
      parameters:
      - description: body biz.Biz for post
        in: body
        name: biz
        required: true
        schema:
          $ref: '#/definitions/biz.Biz'
      produces:
      - application/json
      responses:
        "200":
          description: value in biz.Biz
          schema:
            $ref: '#/definitions/biz.Biz'
        "400":
          description: error at errdef.Err
          schema:
            $ref: '#/definitions/errdef.Err'
      summary: api json struct biz.Biz
      tags:
      - biz
  /biz/modelBizQuery:
    post:
      consumes:
      - application/json
      description: warning api in prod will hide, abs remote api for dev
      parameters:
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      - description: body biz.Biz for post
        in: body
        name: biz
        required: true
        schema:
          $ref: '#/definitions/biz.Biz'
      produces:
      - application/json
      responses:
        "200":
          description: value in biz.Biz
          schema:
            $ref: '#/definitions/biz.Biz'
        "400":
          description: error at errdef.Err
          schema:
            $ref: '#/definitions/errdef.Err'
      summary: api post query with json struct biz.Biz
      tags:
      - biz
  /biz/path/{some_id}:
    get:
      consumes:
      - multipart/form-data
      description: warning api in prod will hide, abs remote api for dev
      parameters:
      - description: some id to show
        in: path
        name: some_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: value in biz.Biz
          schema:
            $ref: '#/definitions/biz.Biz'
        "400":
          description: error at errdef.Err
          schema:
            $ref: '#/definitions/errdef.Err'
      summary: api path demo for route path
      tags:
      - biz
  /biz/query:
    get:
      consumes:
      - application/json
      description: warning api in prod will hide, abs remote api for dev
      parameters:
      - default: 0
        description: Offset
        in: query
        minimum: 0
        name: offset
        required: true
        type: integer
      - default: 10
        description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: value in biz.Biz
          schema:
            $ref: '#/definitions/biz.Biz'
        "400":
          description: error at errdef.Err
          schema:
            $ref: '#/definitions/errdef.Err'
      summary: api demo for query.
      tags:
      - biz
  /biz/query_full:
    get:
      consumes:
      - application/json
      description: for biz
      parameters:
      - default: '""'
        description: 'params foo '
        in: query
        name: foo
        required: true
        type: string
      - default: '""'
        description: 'params bar '
        in: query
        name: bar
        required: true
        type: string
      - default: '""'
        description: 'params baz '
        in: query
        name: baz
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: value in parse_http.QueryContent
          schema:
            $ref: '#/definitions/parse_http.QueryContent'
        "400":
          description: error at errdef.Err
          schema:
            $ref: '#/definitions/errdef.Err'
      summary: /biz/query_full
      tags:
      - biz
  /biz/string:
    get:
      consumes:
      - application/json
      description: get string of this api. warning api in prod will hide, abs remote
        api for dev
      produces:
      - text/plain
      responses:
        "200":
          description: OK
        "500":
          description: ""
      summary: sample demo string
      tags:
      - biz
  /file/upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload file. warning api in prod will hide, abs remote api for
        dev
      operationId: file.upload
      parameters:
      - description: this is a test file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: We need ID!!
          schema:
            $ref: '#/definitions/errdef.Err'
        "404":
          description: Can not find ID
          schema:
            $ref: '#/definitions/errdef.Err'
      summary: Upload file for count file size
      tags:
      - biz
securityDefinitions:
  BasicAuth:
    type: basic
  WithToken:
    description: Please set the token of the API, note that it starts with "Bearer"
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
