name: ci

on:
  push:
    paths-ignore:
      - '**/README.md'
      - '**/doc-dev/*'
    branches:
      # - 'main'
      - 'release-*'
      - '*-feature-*'
      - '*-enhancement-*'
      - '*-hotfix-*'
      - '*-bug-*'
      - '*-documentation-*'
      - 'BF-*'
      - 'FE-*'
      - 'PU-*'
      - 'DOC-*'
    tags:
      - '*' # Push events to matching *, i.e. 1.0.0 v1.0, v20.15.10
  pull_request:
    paths-ignore:
      - '**/README.md'
    types: # https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#pull_request
      - opened
      - reopened
      - closed
    # branches:
    #   - 'main'
    #   - 'release-*'
    #   - 'DOC-*'
    #   - 'hotfix-*'

permissions:
  contents: write
  discussions: write

jobs:
  version:
    name: version
    uses: ./.github/workflows/version.yml

  golang-ci:
    name: golang-ci
    needs:
     - version
    uses: ./.github/workflows/golang-ci.yml

  go-goreleaser-dry-run:
    name: go-goreleaser-dry-run
    needs:
     - golang-ci
    uses: ./.github/workflows/goreleaser-golang.yml
    secrets: inherit
    with:
      dry_run: true

#   go-build-check-main:
#     name: go-build-check-main
#     needs:
#       - version
#       - golang-ci
#     if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) || github.base_ref == 'main' }}
#     uses: ./.github/workflows/go-release-platform.yml
#     secrets: inherit
#     with:
#       version_name: latest
#       go_build_id: ${{ needs.version.outputs.short_sha }}

  docker-bake-basic-all-latest:
    name: docker-bake-basic-all-latest
    needs:
      - version
      - golang-ci
    uses: ./.github/workflows/docker-buildx-bake-hubdocker-latest.yml
    if: ${{ github.ref_type != 'tag' }}
    with:
      # push_remote_flag: ${{ github.ref == 'refs/heads/main' }}
      # push_remote_flag: ${{ github.event.pull_request.merged == true }}
      push_remote_flag: false # not push
      docker_bake_targets: 'image-basic'
    secrets:
      DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"

  # docker-bake-multi-basic-all-latest:
  #   name: docker-bake-multi-basic-all-latest
  #   needs:
  #     - version
  #   uses: ./.github/workflows/docker-buildx-bake-multi-latest.yml
  #   if: ${{ github.ref_type != 'tag' }}
  #   with:
  #     ghcr_package_owner_name: ${{ github.repository_owner }} # required for ghcr.io
  #     # push_remote_flag: ${{ github.ref == 'refs/heads/main' }}
  #     push_remote_flag: ${{ github.event.pull_request.merged == true }}
  #     docker_bake_targets: 'image-basic'
  #   secrets:
  #     DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"

  go-release-platform:
    name: go-release-platform
    needs:
     - version
     - golang-ci
     # - docker-image-tag
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/go-release-platform.yml
    secrets: inherit
    with:
      version_name: ${{ needs.version.outputs.tag_name }}
      # upload_artifact_name: go-release

  # docker-bake-basic-all-tag:
  #   name: docker-bake-basic-all-tag
  #   needs:
  #     - version
  #   uses: ./.github/workflows/docker-buildx-bake-hubdocker-tag.yml
  #   if: startsWith(github.ref, 'refs/tags/')
  #   with:
  #     docker_bake_targets: 'image-basic'
  #     docker-metadata-flavor-suffix: '' # default is '', can add as: -alpine -debian
  #     # push_remote_flag: true # default is true
  #   secrets:
  #     DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"

  # docker-bake-multi-basic-all-tag:
  #   name: docker-bake-multi-basic-all-tag
  #   needs:
  #     - version
  #   uses: ./.github/workflows/docker-buildx-bake-multi-tag.yml
  #   if: startsWith(github.ref, 'refs/tags/')
  #   with:
  #     ghcr_package_owner_name: ${{ github.repository_owner }} # required for ghcr.io
  #     docker_bake_targets: 'image-basic'
  #     docker-metadata-flavor-suffix: '' # default is '', can add as: -alpine -debian
  #     # push_remote_flag: true # default is true
  #   secrets:
  #     DOCKERHUB_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"

  deploy-tag:
    needs:
      - version
      # - docker-bake-multi-basic-all-tag
      - go-release-platform
    name: deploy-tag
    uses: ./.github/workflows/deploy-tag.yml
    if: startsWith(github.ref, 'refs/tags/')
    secrets: inherit
    with:
      prerelease: true
      tag_name: ${{ needs.version.outputs.tag_name }}
      tag_changes: ${{ needs.version.outputs.cc_changes }}
      # download_artifact_name: go-release